/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as SetupLicenseRouteImport } from './routes/setup/license'
import { Route as DashboardWarehousesRouteImport } from './routes/_dashboard/warehouses'
import { Route as DashboardSuppliersRouteImport } from './routes/_dashboard/suppliers'
import { Route as DashboardRequisitionsRouteImport } from './routes/_dashboard/requisitions'
import { Route as DashboardRecurringRouteImport } from './routes/_dashboard/recurring'
import { Route as DashboardProductsRouteImport } from './routes/_dashboard/products'
import { Route as DashboardPaymentsRouteImport } from './routes/_dashboard/payments'
import { Route as DashboardNotificationsRouteImport } from './routes/_dashboard/notifications'
import { Route as DashboardInvoicesRouteImport } from './routes/_dashboard/invoices'
import { Route as DashboardForecastingRouteImport } from './routes/_dashboard/forecasting'
import { Route as DashboardEinvoiceRouteImport } from './routes/_dashboard/einvoice'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCustomersRouteImport } from './routes/_dashboard/customers'
import { Route as DashboardCostCentersRouteImport } from './routes/_dashboard/cost-centers'
import { Route as DashboardAuditRouteImport } from './routes/_dashboard/audit'
import { Route as DashboardAssetsRouteImport } from './routes/_dashboard/assets'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/_dashboard/reports/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/_dashboard/orders/index'
import { Route as DashboardInventoryIndexRouteImport } from './routes/_dashboard/inventory/index'
import { Route as DashboardSettingsUsersRouteImport } from './routes/_dashboard/settings/users'
import { Route as DashboardSettingsRolesRouteImport } from './routes/_dashboard/settings/roles'
import { Route as DashboardSettingsProfileRouteImport } from './routes/_dashboard/settings/profile'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/_dashboard/settings/notifications'
import { Route as DashboardSettingsLocalizationRouteImport } from './routes/_dashboard/settings/localization'
import { Route as DashboardSettingsCurrenciesRouteImport } from './routes/_dashboard/settings/currencies'
import { Route as DashboardSettingsCompanyRouteImport } from './routes/_dashboard/settings/company'
import { Route as DashboardSettingsAppearanceRouteImport } from './routes/_dashboard/settings/appearance'
import { Route as DashboardReportsSalesRouteImport } from './routes/_dashboard/reports/sales'
import { Route as DashboardReportsInventoryRouteImport } from './routes/_dashboard/reports/inventory'
import { Route as DashboardReportsFinancialRouteImport } from './routes/_dashboard/reports/financial'
import { Route as DashboardReportsCostAccountingRouteImport } from './routes/_dashboard/reports/cost-accounting'
import { Route as DashboardProductsCategoriesRouteImport } from './routes/_dashboard/products/categories'
import { Route as DashboardOrdersSalesRouteImport } from './routes/_dashboard/orders/sales'
import { Route as DashboardOrdersPurchaseRouteImport } from './routes/_dashboard/orders/purchase'
import { Route as DashboardInventoryMovementsRouteImport } from './routes/_dashboard/inventory/movements'
import { Route as DashboardInventoryAdjustmentsRouteImport } from './routes/_dashboard/inventory/adjustments'
import { Route as DashboardAiChatRouteImport } from './routes/_dashboard/ai/chat'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SetupLicenseRoute = SetupLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => SetupRoute,
} as any)
const DashboardWarehousesRoute = DashboardWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuppliersRoute = DashboardSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequisitionsRoute = DashboardRequisitionsRouteImport.update({
  id: '/requisitions',
  path: '/requisitions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecurringRoute = DashboardRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastingRoute = DashboardForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEinvoiceRoute = DashboardEinvoiceRouteImport.update({
  id: '/einvoice',
  path: '/einvoice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCostCentersRoute = DashboardCostCentersRouteImport.update({
  id: '/cost-centers',
  path: '/cost-centers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssetsRoute = DashboardAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryIndexRoute = DashboardInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsUsersRoute = DashboardSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRolesRoute = DashboardSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsLocalizationRoute =
  DashboardSettingsLocalizationRouteImport.update({
    id: '/settings/localization',
    path: '/settings/localization',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsCurrenciesRoute =
  DashboardSettingsCurrenciesRouteImport.update({
    id: '/settings/currencies',
    path: '/settings/currencies',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsCompanyRoute =
  DashboardSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsAppearanceRoute =
  DashboardSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsSalesRoute = DashboardReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsInventoryRoute =
  DashboardReportsInventoryRouteImport.update({
    id: '/reports/inventory',
    path: '/reports/inventory',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsFinancialRoute =
  DashboardReportsFinancialRouteImport.update({
    id: '/reports/financial',
    path: '/reports/financial',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsCostAccountingRoute =
  DashboardReportsCostAccountingRouteImport.update({
    id: '/reports/cost-accounting',
    path: '/reports/cost-accounting',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsCategoriesRoute =
  DashboardProductsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => DashboardProductsRoute,
  } as any)
const DashboardOrdersSalesRoute = DashboardOrdersSalesRouteImport.update({
  id: '/orders/sales',
  path: '/orders/sales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersPurchaseRoute = DashboardOrdersPurchaseRouteImport.update({
  id: '/orders/purchase',
  path: '/orders/purchase',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryMovementsRoute =
  DashboardInventoryMovementsRouteImport.update({
    id: '/inventory/movements',
    path: '/inventory/movements',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryAdjustmentsRoute =
  DashboardInventoryAdjustmentsRouteImport.update({
    id: '/inventory/adjustments',
    path: '/inventory/adjustments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAiChatRoute = DashboardAiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/assets': typeof DashboardAssetsRoute
  '/audit': typeof DashboardAuditRoute
  '/cost-centers': typeof DashboardCostCentersRoute
  '/customers': typeof DashboardCustomersRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/einvoice': typeof DashboardEinvoiceRoute
  '/forecasting': typeof DashboardForecastingRoute
  '/invoices': typeof DashboardInvoicesRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/payments': typeof DashboardPaymentsRoute
  '/products': typeof DashboardProductsRouteWithChildren
  '/recurring': typeof DashboardRecurringRoute
  '/requisitions': typeof DashboardRequisitionsRoute
  '/suppliers': typeof DashboardSuppliersRoute
  '/warehouses': typeof DashboardWarehousesRoute
  '/setup/license': typeof SetupLicenseRoute
  '/setup/': typeof SetupIndexRoute
  '/ai/chat': typeof DashboardAiChatRoute
  '/inventory/adjustments': typeof DashboardInventoryAdjustmentsRoute
  '/inventory/movements': typeof DashboardInventoryMovementsRoute
  '/orders/purchase': typeof DashboardOrdersPurchaseRoute
  '/orders/sales': typeof DashboardOrdersSalesRoute
  '/products/categories': typeof DashboardProductsCategoriesRoute
  '/reports/cost-accounting': typeof DashboardReportsCostAccountingRoute
  '/reports/financial': typeof DashboardReportsFinancialRoute
  '/reports/inventory': typeof DashboardReportsInventoryRoute
  '/reports/sales': typeof DashboardReportsSalesRoute
  '/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/settings/company': typeof DashboardSettingsCompanyRoute
  '/settings/currencies': typeof DashboardSettingsCurrenciesRoute
  '/settings/localization': typeof DashboardSettingsLocalizationRoute
  '/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/settings/profile': typeof DashboardSettingsProfileRoute
  '/settings/roles': typeof DashboardSettingsRolesRoute
  '/settings/users': typeof DashboardSettingsUsersRoute
  '/inventory': typeof DashboardInventoryIndexRoute
  '/orders': typeof DashboardOrdersIndexRoute
  '/reports': typeof DashboardReportsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assets': typeof DashboardAssetsRoute
  '/audit': typeof DashboardAuditRoute
  '/cost-centers': typeof DashboardCostCentersRoute
  '/customers': typeof DashboardCustomersRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/einvoice': typeof DashboardEinvoiceRoute
  '/forecasting': typeof DashboardForecastingRoute
  '/invoices': typeof DashboardInvoicesRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/payments': typeof DashboardPaymentsRoute
  '/products': typeof DashboardProductsRouteWithChildren
  '/recurring': typeof DashboardRecurringRoute
  '/requisitions': typeof DashboardRequisitionsRoute
  '/suppliers': typeof DashboardSuppliersRoute
  '/warehouses': typeof DashboardWarehousesRoute
  '/setup/license': typeof SetupLicenseRoute
  '/setup': typeof SetupIndexRoute
  '/ai/chat': typeof DashboardAiChatRoute
  '/inventory/adjustments': typeof DashboardInventoryAdjustmentsRoute
  '/inventory/movements': typeof DashboardInventoryMovementsRoute
  '/orders/purchase': typeof DashboardOrdersPurchaseRoute
  '/orders/sales': typeof DashboardOrdersSalesRoute
  '/products/categories': typeof DashboardProductsCategoriesRoute
  '/reports/cost-accounting': typeof DashboardReportsCostAccountingRoute
  '/reports/financial': typeof DashboardReportsFinancialRoute
  '/reports/inventory': typeof DashboardReportsInventoryRoute
  '/reports/sales': typeof DashboardReportsSalesRoute
  '/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/settings/company': typeof DashboardSettingsCompanyRoute
  '/settings/currencies': typeof DashboardSettingsCurrenciesRoute
  '/settings/localization': typeof DashboardSettingsLocalizationRoute
  '/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/settings/profile': typeof DashboardSettingsProfileRoute
  '/settings/roles': typeof DashboardSettingsRolesRoute
  '/settings/users': typeof DashboardSettingsUsersRoute
  '/inventory': typeof DashboardInventoryIndexRoute
  '/orders': typeof DashboardOrdersIndexRoute
  '/reports': typeof DashboardReportsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/_dashboard/assets': typeof DashboardAssetsRoute
  '/_dashboard/audit': typeof DashboardAuditRoute
  '/_dashboard/cost-centers': typeof DashboardCostCentersRoute
  '/_dashboard/customers': typeof DashboardCustomersRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/einvoice': typeof DashboardEinvoiceRoute
  '/_dashboard/forecasting': typeof DashboardForecastingRoute
  '/_dashboard/invoices': typeof DashboardInvoicesRoute
  '/_dashboard/notifications': typeof DashboardNotificationsRoute
  '/_dashboard/payments': typeof DashboardPaymentsRoute
  '/_dashboard/products': typeof DashboardProductsRouteWithChildren
  '/_dashboard/recurring': typeof DashboardRecurringRoute
  '/_dashboard/requisitions': typeof DashboardRequisitionsRoute
  '/_dashboard/suppliers': typeof DashboardSuppliersRoute
  '/_dashboard/warehouses': typeof DashboardWarehousesRoute
  '/setup/license': typeof SetupLicenseRoute
  '/setup/': typeof SetupIndexRoute
  '/_dashboard/ai/chat': typeof DashboardAiChatRoute
  '/_dashboard/inventory/adjustments': typeof DashboardInventoryAdjustmentsRoute
  '/_dashboard/inventory/movements': typeof DashboardInventoryMovementsRoute
  '/_dashboard/orders/purchase': typeof DashboardOrdersPurchaseRoute
  '/_dashboard/orders/sales': typeof DashboardOrdersSalesRoute
  '/_dashboard/products/categories': typeof DashboardProductsCategoriesRoute
  '/_dashboard/reports/cost-accounting': typeof DashboardReportsCostAccountingRoute
  '/_dashboard/reports/financial': typeof DashboardReportsFinancialRoute
  '/_dashboard/reports/inventory': typeof DashboardReportsInventoryRoute
  '/_dashboard/reports/sales': typeof DashboardReportsSalesRoute
  '/_dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/_dashboard/settings/company': typeof DashboardSettingsCompanyRoute
  '/_dashboard/settings/currencies': typeof DashboardSettingsCurrenciesRoute
  '/_dashboard/settings/localization': typeof DashboardSettingsLocalizationRoute
  '/_dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/_dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/_dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/_dashboard/settings/users': typeof DashboardSettingsUsersRoute
  '/_dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/_dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/_dashboard/reports/': typeof DashboardReportsIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/assets'
    | '/audit'
    | '/cost-centers'
    | '/customers'
    | '/dashboard'
    | '/einvoice'
    | '/forecasting'
    | '/invoices'
    | '/notifications'
    | '/payments'
    | '/products'
    | '/recurring'
    | '/requisitions'
    | '/suppliers'
    | '/warehouses'
    | '/setup/license'
    | '/setup/'
    | '/ai/chat'
    | '/inventory/adjustments'
    | '/inventory/movements'
    | '/orders/purchase'
    | '/orders/sales'
    | '/products/categories'
    | '/reports/cost-accounting'
    | '/reports/financial'
    | '/reports/inventory'
    | '/reports/sales'
    | '/settings/appearance'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/localization'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/users'
    | '/inventory'
    | '/orders'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assets'
    | '/audit'
    | '/cost-centers'
    | '/customers'
    | '/dashboard'
    | '/einvoice'
    | '/forecasting'
    | '/invoices'
    | '/notifications'
    | '/payments'
    | '/products'
    | '/recurring'
    | '/requisitions'
    | '/suppliers'
    | '/warehouses'
    | '/setup/license'
    | '/setup'
    | '/ai/chat'
    | '/inventory/adjustments'
    | '/inventory/movements'
    | '/orders/purchase'
    | '/orders/sales'
    | '/products/categories'
    | '/reports/cost-accounting'
    | '/reports/financial'
    | '/reports/inventory'
    | '/reports/sales'
    | '/settings/appearance'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/localization'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/users'
    | '/inventory'
    | '/orders'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/setup'
    | '/_dashboard/assets'
    | '/_dashboard/audit'
    | '/_dashboard/cost-centers'
    | '/_dashboard/customers'
    | '/_dashboard/dashboard'
    | '/_dashboard/einvoice'
    | '/_dashboard/forecasting'
    | '/_dashboard/invoices'
    | '/_dashboard/notifications'
    | '/_dashboard/payments'
    | '/_dashboard/products'
    | '/_dashboard/recurring'
    | '/_dashboard/requisitions'
    | '/_dashboard/suppliers'
    | '/_dashboard/warehouses'
    | '/setup/license'
    | '/setup/'
    | '/_dashboard/ai/chat'
    | '/_dashboard/inventory/adjustments'
    | '/_dashboard/inventory/movements'
    | '/_dashboard/orders/purchase'
    | '/_dashboard/orders/sales'
    | '/_dashboard/products/categories'
    | '/_dashboard/reports/cost-accounting'
    | '/_dashboard/reports/financial'
    | '/_dashboard/reports/inventory'
    | '/_dashboard/reports/sales'
    | '/_dashboard/settings/appearance'
    | '/_dashboard/settings/company'
    | '/_dashboard/settings/currencies'
    | '/_dashboard/settings/localization'
    | '/_dashboard/settings/notifications'
    | '/_dashboard/settings/profile'
    | '/_dashboard/settings/roles'
    | '/_dashboard/settings/users'
    | '/_dashboard/inventory/'
    | '/_dashboard/orders/'
    | '/_dashboard/reports/'
    | '/_dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/license': {
      id: '/setup/license'
      path: '/license'
      fullPath: '/setup/license'
      preLoaderRoute: typeof SetupLicenseRouteImport
      parentRoute: typeof SetupRoute
    }
    '/_dashboard/warehouses': {
      id: '/_dashboard/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof DashboardWarehousesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/suppliers': {
      id: '/_dashboard/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof DashboardSuppliersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/requisitions': {
      id: '/_dashboard/requisitions'
      path: '/requisitions'
      fullPath: '/requisitions'
      preLoaderRoute: typeof DashboardRequisitionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/recurring': {
      id: '/_dashboard/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof DashboardRecurringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products': {
      id: '/_dashboard/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/payments': {
      id: '/_dashboard/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/notifications': {
      id: '/_dashboard/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/invoices': {
      id: '/_dashboard/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/forecasting': {
      id: '/_dashboard/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof DashboardForecastingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/einvoice': {
      id: '/_dashboard/einvoice'
      path: '/einvoice'
      fullPath: '/einvoice'
      preLoaderRoute: typeof DashboardEinvoiceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/customers': {
      id: '/_dashboard/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cost-centers': {
      id: '/_dashboard/cost-centers'
      path: '/cost-centers'
      fullPath: '/cost-centers'
      preLoaderRoute: typeof DashboardCostCentersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/audit': {
      id: '/_dashboard/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/assets': {
      id: '/_dashboard/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof DashboardAssetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/': {
      id: '/_dashboard/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/orders/': {
      id: '/_dashboard/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inventory/': {
      id: '/_dashboard/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof DashboardInventoryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/users': {
      id: '/_dashboard/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof DashboardSettingsUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/roles': {
      id: '/_dashboard/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof DashboardSettingsRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/profile': {
      id: '/_dashboard/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/notifications': {
      id: '/_dashboard/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/localization': {
      id: '/_dashboard/settings/localization'
      path: '/settings/localization'
      fullPath: '/settings/localization'
      preLoaderRoute: typeof DashboardSettingsLocalizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/currencies': {
      id: '/_dashboard/settings/currencies'
      path: '/settings/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof DashboardSettingsCurrenciesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/company': {
      id: '/_dashboard/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof DashboardSettingsCompanyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/appearance': {
      id: '/_dashboard/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/sales': {
      id: '/_dashboard/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof DashboardReportsSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/inventory': {
      id: '/_dashboard/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof DashboardReportsInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/financial': {
      id: '/_dashboard/reports/financial'
      path: '/reports/financial'
      fullPath: '/reports/financial'
      preLoaderRoute: typeof DashboardReportsFinancialRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/cost-accounting': {
      id: '/_dashboard/reports/cost-accounting'
      path: '/reports/cost-accounting'
      fullPath: '/reports/cost-accounting'
      preLoaderRoute: typeof DashboardReportsCostAccountingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/categories': {
      id: '/_dashboard/products/categories'
      path: '/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof DashboardProductsCategoriesRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
    '/_dashboard/orders/sales': {
      id: '/_dashboard/orders/sales'
      path: '/orders/sales'
      fullPath: '/orders/sales'
      preLoaderRoute: typeof DashboardOrdersSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/orders/purchase': {
      id: '/_dashboard/orders/purchase'
      path: '/orders/purchase'
      fullPath: '/orders/purchase'
      preLoaderRoute: typeof DashboardOrdersPurchaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inventory/movements': {
      id: '/_dashboard/inventory/movements'
      path: '/inventory/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof DashboardInventoryMovementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inventory/adjustments': {
      id: '/_dashboard/inventory/adjustments'
      path: '/inventory/adjustments'
      fullPath: '/inventory/adjustments'
      preLoaderRoute: typeof DashboardInventoryAdjustmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ai/chat': {
      id: '/_dashboard/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof DashboardAiChatRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardProductsRouteChildren {
  DashboardProductsCategoriesRoute: typeof DashboardProductsCategoriesRoute
}

const DashboardProductsRouteChildren: DashboardProductsRouteChildren = {
  DashboardProductsCategoriesRoute: DashboardProductsCategoriesRoute,
}

const DashboardProductsRouteWithChildren =
  DashboardProductsRoute._addFileChildren(DashboardProductsRouteChildren)

interface DashboardRouteChildren {
  DashboardAssetsRoute: typeof DashboardAssetsRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardCostCentersRoute: typeof DashboardCostCentersRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardEinvoiceRoute: typeof DashboardEinvoiceRoute
  DashboardForecastingRoute: typeof DashboardForecastingRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProductsRoute: typeof DashboardProductsRouteWithChildren
  DashboardRecurringRoute: typeof DashboardRecurringRoute
  DashboardRequisitionsRoute: typeof DashboardRequisitionsRoute
  DashboardSuppliersRoute: typeof DashboardSuppliersRoute
  DashboardWarehousesRoute: typeof DashboardWarehousesRoute
  DashboardAiChatRoute: typeof DashboardAiChatRoute
  DashboardInventoryAdjustmentsRoute: typeof DashboardInventoryAdjustmentsRoute
  DashboardInventoryMovementsRoute: typeof DashboardInventoryMovementsRoute
  DashboardOrdersPurchaseRoute: typeof DashboardOrdersPurchaseRoute
  DashboardOrdersSalesRoute: typeof DashboardOrdersSalesRoute
  DashboardReportsCostAccountingRoute: typeof DashboardReportsCostAccountingRoute
  DashboardReportsFinancialRoute: typeof DashboardReportsFinancialRoute
  DashboardReportsInventoryRoute: typeof DashboardReportsInventoryRoute
  DashboardReportsSalesRoute: typeof DashboardReportsSalesRoute
  DashboardSettingsAppearanceRoute: typeof DashboardSettingsAppearanceRoute
  DashboardSettingsCompanyRoute: typeof DashboardSettingsCompanyRoute
  DashboardSettingsCurrenciesRoute: typeof DashboardSettingsCurrenciesRoute
  DashboardSettingsLocalizationRoute: typeof DashboardSettingsLocalizationRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsRolesRoute: typeof DashboardSettingsRolesRoute
  DashboardSettingsUsersRoute: typeof DashboardSettingsUsersRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssetsRoute: DashboardAssetsRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardCostCentersRoute: DashboardCostCentersRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardEinvoiceRoute: DashboardEinvoiceRoute,
  DashboardForecastingRoute: DashboardForecastingRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProductsRoute: DashboardProductsRouteWithChildren,
  DashboardRecurringRoute: DashboardRecurringRoute,
  DashboardRequisitionsRoute: DashboardRequisitionsRoute,
  DashboardSuppliersRoute: DashboardSuppliersRoute,
  DashboardWarehousesRoute: DashboardWarehousesRoute,
  DashboardAiChatRoute: DashboardAiChatRoute,
  DashboardInventoryAdjustmentsRoute: DashboardInventoryAdjustmentsRoute,
  DashboardInventoryMovementsRoute: DashboardInventoryMovementsRoute,
  DashboardOrdersPurchaseRoute: DashboardOrdersPurchaseRoute,
  DashboardOrdersSalesRoute: DashboardOrdersSalesRoute,
  DashboardReportsCostAccountingRoute: DashboardReportsCostAccountingRoute,
  DashboardReportsFinancialRoute: DashboardReportsFinancialRoute,
  DashboardReportsInventoryRoute: DashboardReportsInventoryRoute,
  DashboardReportsSalesRoute: DashboardReportsSalesRoute,
  DashboardSettingsAppearanceRoute: DashboardSettingsAppearanceRoute,
  DashboardSettingsCompanyRoute: DashboardSettingsCompanyRoute,
  DashboardSettingsCurrenciesRoute: DashboardSettingsCurrenciesRoute,
  DashboardSettingsLocalizationRoute: DashboardSettingsLocalizationRoute,
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardSettingsRolesRoute: DashboardSettingsRolesRoute,
  DashboardSettingsUsersRoute: DashboardSettingsUsersRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SetupRouteChildren {
  SetupLicenseRoute: typeof SetupLicenseRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupLicenseRoute: SetupLicenseRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
